#pragma once

#define EMIT_COLOR_BLACK 1
#define EMIT_COLOR_RED 2
#define EMIT_COLOR_GREEN 3
#define EMIT_COLOR_YELLOW 4
#define EMIT_COLOR_BLUE 5
#define EMIT_COLOR_MAGENTA 6
#define EMIT_COLOR_CYAN 7
#define EMIT_COLOR_WHITE 8

#define EMIT_DECORATOR_RESET 1
#define EMIT_DECORATOR_BOLD 2
#define EMIT_DECORATOR_UNDERLINE 4
#define EMIT_DECORATOR_REVERSED 8